// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk3Y7jVCVj4CBM7rsnQ6LOFErPT2ejkSY',
    appId: '1:759904501110:web:b6dac978b62aa27d028e57',
    messagingSenderId: '759904501110',
    projectId: 'film-edc60',
    authDomain: 'film-edc60.firebaseapp.com',
    storageBucket: 'film-edc60.firebasestorage.app',
    measurementId: 'G-9HPCWN8TVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqgYtfYKUmXS1LbkpKuZvSowNojfrjzYY',
    appId: '1:759904501110:android:dc1928ea0788cbd6028e57',
    messagingSenderId: '759904501110',
    projectId: 'film-edc60',
    storageBucket: 'film-edc60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChIAb6e7hvh3dyDDO3gl6IVYcilf3nvtc',
    appId: '1:759904501110:ios:cda356292ca238cb028e57',
    messagingSenderId: '759904501110',
    projectId: 'film-edc60',
    storageBucket: 'film-edc60.firebasestorage.app',
    iosBundleId: 'com.example.filmManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChIAb6e7hvh3dyDDO3gl6IVYcilf3nvtc',
    appId: '1:759904501110:ios:cda356292ca238cb028e57',
    messagingSenderId: '759904501110',
    projectId: 'film-edc60',
    storageBucket: 'film-edc60.firebasestorage.app',
    iosBundleId: 'com.example.filmManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk3Y7jVCVj4CBM7rsnQ6LOFErPT2ejkSY',
    appId: '1:759904501110:web:accbf6031ec77a36028e57',
    messagingSenderId: '759904501110',
    projectId: 'film-edc60',
    authDomain: 'film-edc60.firebaseapp.com',
    storageBucket: 'film-edc60.firebasestorage.app',
    measurementId: 'G-M78Q6RBY56',
  );
}
